import from dgcode git: version 2.2.0

diff --git a/ncrystal_mcstas/ncrystal_preparemcstasdir b/ncrystal_mcstas/ncrystal_preparemcstasdir
--- a/ncrystal_mcstas/ncrystal_preparemcstasdir
+++ b/ncrystal_mcstas/ncrystal_preparemcstasdir
@@ -34,24 +34,58 @@ if [ -f ./$nccompfn ]; then
     exit 1
 fi
 
-if [ "${NCRYSTALDIR-none}" == "none" ]; then
-    echo "NCRYSTALDIR environment variable not set. Did you remember to source the setup.sh script from NCrystal?"
+
+thisdir="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+nccfgcmd="ncrystal-config"
+needs_nc_setup=0
+if ! command -v ncrystal-config >/dev/null 2>&1; then
+    if [ -f "${thisdir}/ncrystal-config" ]; then
+        export PATH="${thisdir}:$PATH"
+        needs_nc_setup=1
+    fi
+fi
+if ! command -v ncrystal-config >/dev/null 2>&1; then
+    echo "ncrystal-config command not found."
     exit 1
 fi
 
-THISDIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-NCMCSTASDIR="$( cd -P "$THISDIR"/../mcstas && pwd )"
+mcstasdir="$(ncrystal-config --show=mcstasdir)"
+incdir="$(ncrystal-config --show=includedir)"
+libpath="$(ncrystal-config --show=libpath)"
 
-if [ "${NCRYSTALDIR+x}" == "x" -a -f "$NCMCSTASDIR/NCrystal_sample.comp" ]; then
-    ln -s "$NCRYSTALDIR" ./NCrystalLink
-    ln -s "$NCMCSTASDIR/NCrystal_sample.comp" .
-    echo "Succesfully linked NCrystal_sample.comp to current directory and added NCrystalLink which is needed for instrument build."
-else
-    #A bit weird that the user has the current script but not the NCrystal_sample.comp file.
-    echo "ERROR: Did not find NCrystal_sample.comp in your installation."
+if [ ! -f "$mcstasdir/${nccompfn}" ]; then
+    echo "Did not find the ${nccompfn} file (expected it in $mcstasdir due to output from ncrystal-config)."
     exit 1
 fi
 
-if [ "${NCRYSTALDIR+x}" == "x" -a -f "$NCMCSTASDIR/NCrystal_example_mcstas.instr" ]; then
-    echo "Note that an example instrument file using NCrystal_sample.comp can be found here: $NCMCSTASDIR/NCrystal_example_mcstas.instr"
+if [ ! -f "$incdir/NCrystal/ncrystal.h" ]; then
+    echo "Did not find the NCrystal/ncrystal.h file (expected it in $incdir due to output from ncrystal-config)."
+    exit 1
+fi
+
+if [ ! -f "$libpath" ]; then
+    echo "Did not find the NCrystal library (expected it in the location $libpath due to output from ncrystal-config)."
+    exit 1
+fi
+
+mkdir -p NCrystalLink/lib NCrystalLink/include/NCrystal
+ln -s "$libpath" NCrystalLink/lib/
+ln -s "$incdir/NCrystal/ncrystal.h" NCrystalLink/include/NCrystal/
+ln -s "$incdir/NCrystal/ncapi.h" NCrystalLink/include/NCrystal/
+ln -s "$mcstasdir/${nccompfn}" .
+
+echo "Succesfully linked ${nccompfn} to current directory and added NCrystalLink which is needed for instrument build."
+
+if [ -f "$mcstasdir/NCrystal_example_mcstas.instr" ]; then
+    echo "Note that an example instrument file using ${nccompfn} can be found here: $mcstasdir/NCrystal_example_mcstas.instr"
+fi
+
+if [ $needs_nc_setup == 1 ]; then
+    echo
+    echo "WARNING: you might not have a correctly setup NCrystal environment."
+    echo
+    echo "You might be able to fix it by typing the following command (including all special characters):"
+    echo
+    echo '  $("'"${thisdir}/ncrystal-config"'" --setup)'
+    echo
 fi
